apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
  namespace: argocd
data:
  registries.conf: |
    registries:
      - name: Google Artifact Registry
        prefix: us-central1-docker.pkg.dev
        api_url: https://us-central1-docker.pkg.dev
        credentials: ext:/app/auth/auth.sh
        credsexpire: 45m
        default: false